name: Lint
on:
  push:
    branches:
      - '**'

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck
